#!/usr/bin/env python3
"""
October Grants - Targeted Grants for Integration
Generated from October grants CSV processing
"""

# Additional targeted grants from October grants list
OCTOBER_TARGETED_GRANTS = {
    'NLM_Information_Resource_Grants_to_Reduce_Health_D': {
        'amount': 'Up to $$600,000',
        'focus': 'Business development and community support - Health and Human Services',
        'url': 'Website',
        'keywords': ['economic development', 'business development', 'health and human services', 'entrepreneurship'],
        'deadline_type': 'specific_date',
        'deadline': '11/13/2024',
        'category': 'minority_business',
        'priority': 'MEDIUM',
        'source': 'october_grants_csv',
    },
    'Providing_Research_Education_Experiences_to_Enhanc': {
        'amount': 'Up to $$1,250,000',
        'focus': 'Business development and community support - Public Safety and Disaster Relief',
        'url': 'Website',
        'keywords': ['entrepreneurship', 'public safety and disaster relief', 'economic development', 'business development', 'education'],
        'deadline_type': 'specific_date',
        'deadline': '11/13/2024',
        'category': 'minority_business',
        'priority': 'MEDIUM',
        'source': 'october_grants_csv',
    },
    'Foundation_for_Global_Sports_Development:_Athletes': {
        'amount': '$$10,000',
        'focus': 'Economic empowerment and financial education - Public Safety and Disaster Relief',
        'url': 'Website',
        'keywords': ['financial education', 'public safety and disaster relief', 'economic empowerment', 'development', 'financial literacy'],
        'deadline_type': 'specific_date',
        'deadline': '11/1/2024',
        'category': 'financial_literacy',
        'priority': 'MEDIUM',
        'source': 'october_grants_csv',
    },
    'NIA_Research_and_Entrepreneurial_Development_Immer': {
        'amount': 'Up to $$140,000',
        'focus': 'Economic empowerment and financial education - Public Safety and Disaster Relief',
        'url': 'Website',
        'keywords': ['financial education', 'public safety and disaster relief', 'economic empowerment', 'development', 'financial literacy'],
        'deadline_type': 'specific_date',
        'deadline': '11/15/2024',
        'category': 'financial_literacy',
        'priority': 'MEDIUM',
        'source': 'october_grants_csv',
    },
    'California_Department_of_Health_Care_Access_and_In': {
        'amount': 'Up to $$25,000',
        'focus': 'Technology innovation and digital advancement - Health and Human Services',
        'url': 'Website',
        'keywords': ['digital', 'technology', 'health and human services', 'innovation'],
        'deadline_type': 'specific_date',
        'deadline': '10/16/2024',
        'category': 'technology',
        'priority': 'MEDIUM',
        'source': 'october_grants_csv',
    },
    'Early-stage_Biomedical_Data_Repositories_and_Knowl': {
        'amount': 'Up to $$1,400,000',
        'focus': 'Technology innovation and digital advancement - Health and Human Services',
        'url': 'Website',
        'keywords': ['digital', 'technology', 'health and human services', 'innovation'],
        'deadline_type': 'specific_date',
        'deadline': '11/26/2024',
        'category': 'technology',
        'priority': 'MEDIUM',
        'source': 'october_grants_csv',
    },
    'Enhancement_and_Management_of_Established_Biomedic': {
        'amount': 'Varies',
        'focus': 'Technology innovation and digital advancement - Health and Human Services',
        'url': 'Website',
        'keywords': ['digital', 'technology', 'health and human services', 'innovation'],
        'deadline_type': 'specific_date',
        'deadline': '11/26/2024',
        'category': 'technology',
        'priority': 'MEDIUM',
        'source': 'october_grants_csv',
    },
    'Equity_in_Mathematics_Grant_PK-6': {
        'amount': 'Up to $$8,000',
        'focus': 'Youth development and educational support - Education',
        'url': 'Website',
        'keywords': ['youth development', 'education', 'learning'],
        'deadline_type': 'specific_date',
        'deadline': '11/1/2024',
        'category': 'youth_empowerment',
        'priority': 'HIGH',
        'source': 'october_grants_csv',
    },
    'Equity_in_Mathematics_Grants_6-12': {
        'amount': 'Up to $$8,000',
        'focus': 'Youth development and educational support - Education',
        'url': 'Website',
        'keywords': ['youth development', 'education', 'learning'],
        'deadline_type': 'specific_date',
        'deadline': '11/1/2024',
        'category': 'youth_empowerment',
        'priority': 'HIGH',
        'source': 'october_grants_csv',
    },
    'Office_of_Elementary_and_Secondary_Education_OESE:': {
        'amount': '$$180,000 - $$475,000',
        'focus': 'Youth development and educational support - Education',
        'url': 'Website',
        'keywords': ['program', 'youth development', 'education', 'learning'],
        'deadline_type': 'specific_date',
        'deadline': '11/13/2024',
        'category': 'youth_empowerment',
        'priority': 'HIGH',
        'source': 'october_grants_csv',
    },
    'Georgia_Department_of_Community_Affairs': {
        'amount': '$$250,000 - $$2,500,000',
        'focus': 'Community development and local impact - Community Development',
        'url': 'Website',
        'keywords': ['neighborhood', 'local impact', 'community', 'community development'],
        'deadline_type': 'specific_date',
        'deadline': '10/11/2024',
        'category': 'community_development',
        'priority': 'HIGH',
        'source': 'october_grants_csv',
    },
    'National_Association_Of_Realtors': {
        'amount': 'Up to $$15,000',
        'focus': 'Community development and local impact - Community Development',
        'url': 'Website',
        'keywords': ['neighborhood', 'local impact', 'community development'],
        'deadline_type': 'specific_date',
        'deadline': '10/15/2024',
        'category': 'community_development',
        'priority': 'HIGH',
        'source': 'october_grants_csv',
    },
    'Community_Foundation_of_the_Chattahoochee_Valley': {
        'amount': '$$10,000 - $$25,000',
        'focus': 'Community development and local impact - Community Development',
        'url': 'Website',
        'keywords': ['neighborhood', 'local impact', 'community', 'community development'],
        'deadline_type': 'specific_date',
        'deadline': '',
        'category': 'community_development',
        'priority': 'HIGH',
        'source': 'october_grants_csv',
    },
}
